### ISSUE TITLE
teabase文档中资源管理接口部分非文件资源部分提供的接口暂无法使用

### ISSUE THREAD

**Issue by tq0agme** [Tencent/QTAF#10]
https://qta-testbase.readthedocs.io/zh/latest/resource.html#registerrestype
![image](https://user-images.githubusercontent.com/44672512/47853011-6b904b00-de18-11e8-9f7b-bfb73197c10a.png)
这部分接口使用时提示NotImplementError

**Comment by eeelin** [comment]
fixed in https://github.com/Tencent/QTAF/commit/f6ca5a91e75c7f4c8e5ba3675e82e69ec98aba91
