### ISSUE TITLE
执行打包，NameError 异常~

### ISSUE THREAD

**Issue by bruceqiao** [Tencent/QTAF#52]
> 调用测试项目的manage.py:
> 
> $ python manage.py dist --version 1.0.0
> 执行成功后可以看到生成文件在dist目录下:
> 
> dist/
>     foo-1.0.0.tar.gz
本地执行后
```
Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    install_requires=dict_values(['qtaf']),
NameError: name 'dict_values' is not defined
```
MacBook Pro，macOS Mojave

**Comment by guyingzhao** [comment]
fix in commit https://github.com/Tencent/QTAF/commit/dc4eb685c3260896a80e32fb92aed9e953bcb9f2
