### ISSUE TITLE
dist 打出来的包runtest 时 Exception（relative_path not found)

### ISSUE THREAD

**Issue by bruceqiao** [Tencent/QTAF#57]
![image](https://user-images.githubusercontent.com/1934641/56882936-c50bc680-6a97-11e9-9d11-30f17c1d35bc.png)
1. 源文件中含有 resources 文件
2. 打包
3. runtest，发现解压缩出来resources目录不在 lib\python\site-packages\目录下
![image](https://user-images.githubusercontent.com/1934641/56883106-45322c00-6a98-11e9-8557-6f0f14301725.png)

**Comment by guyingzhao** [comment]
fixed by https://github.com/Tencent/QTAF/commit/e8e83a3947f2b2692919c78cc57d38f532807d61
