### ISSUE TITLE
TestPlan().debug_run() 的时候会因为入参retries=None而报错

### ISSUE THREAD

**Issue by CsyDesign** [Tencent/QTAF#65]
![image](https://user-images.githubusercontent.com/50761900/61579249-a3b9f400-ab35-11e9-9f08-577db2b3d2c4.png)

看上去构造函数中retries的默认值0没有起作用
我额外再次赋值后就不再报错了
`if retries is None:retries=0`

后来我发现这样可以更好的解决这个问题
![image](https://user-images.githubusercontent.com/50761900/61579804-a704ae00-ab3c-11e9-9f0e-7262f2f29ea8.png)

**Comment by eeelin** [comment]
fix in #68

**Comment by eeelin** [comment]
fix in version 5.4.32
